feat(guilds): add some roles/invites/other stuff
Discordoo/discordoo pull request #48
Opened 2023-08-17 17:25 UTC by Amirust

2023-08-17 22:16 UTC, Amirust commented
Pls mrg dev in2 master asap!!!!!!

2023-08-17 22:37 UTC, Mirdukkk requested changes
also, no classes and interfaces are exported. they need to be moved to local indexes in the folders in which they are located. you also need to create an ApplicationInvitesManager, and initialize it in DiscordRestApplication.

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/entities/guild/Guild.ts
> +  async edit(data: Partial<RawGuildData>): Promise<this | undefined> {
should use GuildEditData

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/entities/guild/Guild.ts
> +    const success = await this.app.internals.actions.editGuild(this.id, data)
should use app.guilds.create

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/entities/guild/Guild.ts
> +    const success = await this.app.internals.actions.deleteGuild(this.id)
should use app.guilds.delete

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/entities/guild/interfaces/RawGuildCreateData.ts
> +  systemChannelId?: string
should use snake_case

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/managers/ApplicationGuildsManager.ts
> +  async create(data: GuildCreateData): Promise<Guild | undefined> {
GuildCreateData OR RawGuildCreateData

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/managers/ApplicationGuildsManager.ts
> +        'roles',
should resolve roles to raw when using GuildCreateData

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/managers/ApplicationGuildsManager.ts
> +        'channels',
should resolve channels to raw when using GuildCreateData

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/managers/invites/InviteGuildsManager.ts
> +  cache: EntitiesCacheManager<Invite>
public cache

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/managers/invites/InviteGuildsManager.ts
> +      target_application_id: options.targetApplicationId
use attach

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/managers/invites/InviteGuildsManager.ts
> +    const response = await this.app.internals.actions.deleteInvite(inviteCode, reason)
InviteResolvable & 'cannot delete invite without code'

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/managers/roles/GuildRolesManager.ts
> +    return await this.app.roles.fetchOne(this.guildId, id)
no need to use async/await here

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/managers/roles/GuildRolesManager.ts
> +    if (role) await this.cache.set(role.id, role)
cache will be updated automatically. no need to update it here

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/managers/roles/GuildRolesManager.ts
> +    if (updated) await this.cache.set(updated.id, updated)
cache will be updated automatically. no need to update it here

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/managers/roles/GuildRolesManager.ts
> +    if (result) await this.cache.delete(id)
cache will be updated automatically. no need to update it here

2023-08-17 22:37 UTC, Mirdukkk commented on src/core/apps/actions/RestApplicationActions.ts
> +  createGuild(data: RawGuildCreateData) {
add return type

2023-08-17 22:37 UTC, Mirdukkk commented on src/api/managers/roles/GuildRolesManager.ts
> +  async fetch(id: string): Promise<Role | undefined> {
fetch() should automatically decide whether to use fetchOne or fetchMany. also no fetchMany method is present

2023-08-18 14:00 UTC, Mirdukkk commented on src/api/managers/invites/InviteGuildsManager.ts
> +  cache: EntitiesCacheManager<InviteGuild>
```suggestion
  public cache: EntitiesCacheManager<InviteGuild>
```

2023-08-18 14:03 UTC, Mirdukkk requested changes

2023-08-18 14:03 UTC, Mirdukkk commented on src/api/entities/guild/Guild.ts
> +    if (!widgetChannelId) throw new DiscordooError('Guild#setWidgetChannel', 'Cannot set widget channel to unknown channel.')
please rename all errors in this file to the general format: "Cannot do X without id."

2023-08-18 14:11 UTC, Mirdukkk commented on src/api/entities/guild/interfaces/GuildEditData.ts
> +  safetyAlertsChannelId?: string //
```suggestion
  name?: string
  region?: string
  icon?: BufferResolvable
  verificationLevel?: GuildVerificationLevels
  defaultNotifications?: GuildDefaultMessageNotificationLevel
  explicitContentFilter?: GuildExplicitContentFilterLevels
  afkChannelId?: string
  afkTimeout?: number
  systemChannelId?: string
  systemChannelFlags?: number
  rulesChannelId?: string
  publicUpdatesChannelId?: string
  preferredLocale?: DiscordLocale
  features?: GuildFeatures[]
  description?: string
  banner?: BufferResolvable
  splash?: BufferResolvable
  discoverySplash?: BufferResolvable
  ownerId?: string
  widgetEnabled?: boolean
  widgetChannelId?: string
  premiumProgressEnabled?: boolean
  safetyAlertsChannelId?: string
```

2023-08-18 14:29 UTC, Amirust commented
![993961776171462736](https://github.com/ddoodev/discordoo/assets/57226653/39c1644f-1684-47e2-aad2-3d2154a331be)

2023-08-18 14:30 UTC, Mirdukkk approved these changes

2023-08-18 14:30 UTC, merged